#!/usr/bin/env python3
"""Measure the client's fonts and write data/fontmetrics.lua.

The harness lays frames out for real, which means it has to measure strings
for real: a FontString with a left and a right anchor wraps at that width, and
how many lines that takes decides the height of everything anchored below it.

WoW renders a font object at the pixel size named in Fonts.xml, so the advance
of a glyph is advance_units / unitsPerEm * size. That is what this dumps, per
face and per size, for printable ASCII plus the Latin-1 range, along with the
line height from the font's own hhea table.

The TTF is taken out of the archives first and only then off disk: a client
with its loose fonts parked as .disabled renders from the archive, and this
should measure whatever it actually renders with.

Run through extract.py; the module entry point is write().
"""
import io
import os
import sys

from fontTools.ttLib import TTFont

FIRST, LAST = 32, 255


def _load_face(face, client_dir, client):
    """The TTF as bytes: from the archives if they have it, else off disk."""
    if client is not None:
        data = client.read("Fonts\\" + face.upper())
        if data:
            return data, "archive"
    for candidate in (os.path.join(client_dir, "fonts", face),
                      os.path.join(client_dir, "Fonts", face),
                      os.path.join(client_dir, "fonts", face + ".disabled")):
        if os.path.exists(candidate):
            return open(candidate, "rb").read(), os.path.relpath(candidate, client_dir)
    raise SystemExit("no font %s in %s" % (face, client_dir))


def write(wanted, client_dir, client, out_path, face_dir=None):
    """wanted: {face filename: set of pixel sizes}. Writes the Lua table.

    The faces themselves are copied to face_dir, so the renderer draws with
    exactly the file that was measured - a client whose loose fonts are parked
    renders from the archive, and the two are not the same file.
    """
    if face_dir:
        os.makedirs(face_dir, exist_ok=True)
    lines = [
        "-- Generated by extract.py/fontmetrics.py from the client's own fonts.",
        "-- FontMetrics[face][size] = { lineHeight = <px>, default = <px>, [byte] = <px> }",
        "-- Advances are the font's own, scaled to the pixel size WoW renders at.",
        "",
        "FontMetrics = {",
    ]
    report = []
    for face in sorted(wanted):
        data, source = _load_face(face, client_dir, client)
        if face_dir:
            open(os.path.join(face_dir, face), "wb").write(data)
        font = TTFont(io.BytesIO(data), fontNumber=0)
        upem = font["head"].unitsPerEm
        hhea = font["hhea"]
        line_units = hhea.ascent - hhea.descent + hhea.lineGap
        cmap = font.getBestCmap()
        hmtx = font["hmtx"]

        def advance(code):
            name = cmap.get(code) or cmap.get(ord("?"))
            return hmtx[name][0] if name else 0

        lines.append('    ["%s"] = {' % face)
        for size in sorted(wanted[face]):
            scale = size / float(upem)
            lines.append("        [%d] = {" % size)
            lines.append("            lineHeight = %.3f, default = %.3f,"
                         % (line_units * scale, advance(ord("n")) * scale))
            row = []
            for code in range(FIRST, LAST + 1):
                width = advance(code) * scale
                if width:
                    row.append("[%d] = %.3f," % (code, width))
                if len(row) == 6:
                    lines.append("            " + " ".join(row))
                    row = []
            if row:
                lines.append("            " + " ".join(row))
            lines.append("        },")
        lines.append("    },")
        report.append("  %-16s %s  sizes %s" % (face, source,
                                                ",".join(str(s) for s in sorted(wanted[face]))))
    lines += ["}", ""]
    open(out_path, "w").write("\n".join(lines))
    print("metrics: %d faces -> %s" % (len(wanted), os.path.relpath(out_path)))
    for line in report:
        print(line)


if __name__ == "__main__":
    raise SystemExit("run extract.py metrics")
