-- WorldforgedAtlas: every town and city, as a teleport target.
--
-- GENERATED by mod-madosa/tools/towns/build_towns_addon.py from the
-- client's AreaPOI.dbc and WorldMapArea.dbc - re-run the tool rather
-- than editing this file.
--
-- 124 places in 51 zones.
--
-- Positions are zone-relative fractions, 0,0 at the map's top left, the
-- same form Data.lua uses. `area` is the AreaTable id `.go zonexy` takes,
-- and the fractions are what it converts back through - so the pin and the
-- teleport can never disagree about where a town is.

local _, ns = ...

-- 1 city, 2 town, 3 village.
ns.townRanks = {
    [1] = "City",
    [2] = "Town",
    [3] = "Village",
}

-- index -> name, rank
ns.townInfo = {
    [1] = {"Aerie Peak", 2},
    [2] = {"Agmar's Hammer", 2},
    [3] = {"Aldrassil", 2},
    [4] = {"Allerian Stronghold", 2},
    [5] = {"Altar of Sha'tar", 2},
    [6] = {"Amberpine Lodge", 2},
    [7] = {"Angor Fortress", 3},
    [8] = {"Anvilmar", 3},
    [9] = {"Area 52", 2},
    [10] = {"Astranaar", 2},
    [11] = {"Auberdine", 2},
    [12] = {"Azure Watch", 3},
    [13] = {"Blood Watch", 3},
    [14] = {"Bloodhoof Village", 3},
    [15] = {"Booty Bay", 2},
    [16] = {"Bor'gorok Outpost", 2},
    [17] = {"Brill", 3},
    [18] = {"Brunnhildar Village", 2},
    [19] = {"Camp Mojache", 2},
    [20] = {"Camp Narache", 3},
    [21] = {"Camp Oneqwah", 2},
    [22] = {"Camp Taurajo", 2},
    [23] = {"Camp Tunka'lo", 2},
    [24] = {"Camp Winterhoof", 2},
    [25] = {"Cenarion Hold", 2},
    [26] = {"Cenarion Refuge", 2},
    [27] = {"Conquest Hold", 2},
    [28] = {"Cosmowrench", 2},
    [29] = {"Crusaders' Pinnacle", 2},
    [30] = {"Darkshire", 2},
    [31] = {"Darnassus", 1},
    [32] = {"Death's Rise", 2},
    [33] = {"Deathknell", 3},
    [34] = {"Dolanaar", 2},
    [35] = {"Dun Algaz", 3},
    [36] = {"Dun Modr", 3},
    [37] = {"Evergrove", 2},
    [38] = {"Everlook", 2},
    [39] = {"Fairbreeze Village", 3},
    [40] = {"Falcon Watch", 2},
    [41] = {"Falconwing Square", 3},
    [42] = {"Feathermoon Stronghold", 2},
    [43] = {"Fizzcrank Airstrip", 2},
    [44] = {"Fort Wildervar", 2},
    [45] = {"Freewind Post", 2},
    [46] = {"Frosthold", 2},
    [47] = {"Gadgetzan", 2},
    [48] = {"Garadar", 2},
    [49] = {"Goldshire", 3},
    [50] = {"Grom'arsh Crash-Site", 2},
    [51] = {"Grom'gol Base Camp", 2},
    [52] = {"Hammerfall", 2},
    [53] = {"Honor Hold", 2},
    [54] = {"Ironforge", 1},
    [55] = {"K3", 2},
    [56] = {"Kamagua", 2},
    [57] = {"Kargath", 2},
    [58] = {"Lakeshire", 2},
    [59] = {"Menethil Harbor", 2},
    [60] = {"Moa'ki Harbor", 2},
    [61] = {"Moonbrook", 3},
    [62] = {"Mudsprocket", 2},
    [63] = {"Nesingwary Base Camp", 2},
    [64] = {"New Agamand", 2},
    [65] = {"Nijel's Point", 2},
    [66] = {"Northshire Abbey", 3},
    [67] = {"Ogri'la", 2},
    [68] = {"Orebor Harborage", 2},
    [69] = {"Orgrimmar", 1},
    [70] = {"Ratchet", 2},
    [71] = {"Raven Hill", 3},
    [72] = {"Razor Hill", 3},
    [73] = {"Refuge Pointe", 3},
    [74] = {"Sanctum of the Stars", 2},
    [75] = {"Sen'jin Village", 3},
    [76] = {"Sentinel Hill", 2},
    [77] = {"Shadowmoon Village", 2},
    [78] = {"Shadowprey Village", 2},
    [79] = {"Shattrath City", 1},
    [80] = {"Silvermoon City", 1},
    [81] = {"Southshore", 2},
    [82] = {"Splintertree Post", 2},
    [83] = {"Sporeggar", 2},
    [84] = {"Stars' Rest", 2},
    [85] = {"Stonard", 2},
    [86] = {"Stonebreaker Hold", 2},
    [87] = {"Stonetalon Peak", 2},
    [88] = {"Stormwind City", 1},
    [89] = {"Sun Rock Retreat", 2},
    [90] = {"Swamprat Post", 2},
    [91] = {"Sylvanaar", 2},
    [92] = {"Tarren Mill", 2},
    [93] = {"Taunka'le Village", 2},
    [94] = {"Telaar", 2},
    [95] = {"Telredor", 2},
    [96] = {"Temple of Telhamat", 2},
    [97] = {"Thalanaar", 2},
    [98] = {"The Argent Stand", 2},
    [99] = {"The Crossroads", 2},
    [100] = {"The Den", 3},
    [101] = {"The Exodar", 1},
    [102] = {"The Sepulcher", 2},
    [103] = {"The Shadow Vault", 2},
    [104] = {"The Stormspire", 2},
    [105] = {"Thelsamar", 2},
    [106] = {"Theramore Isle", 2},
    [107] = {"Thrallmar", 2},
    [108] = {"Thunder Bluff", 1},
    [109] = {"Thunderlord Stronghold", 2},
    [110] = {"Toshley's Station", 2},
    [111] = {"Tranquillien", 2},
    [112] = {"Unu'pe", 2},
    [113] = {"Valgarde", 2},
    [114] = {"Valiance Keep", 2},
    [115] = {"Vengeance Landing", 2},
    [116] = {"Venomspite", 2},
    [117] = {"Warsong Hold", 2},
    [118] = {"Westfall Brigade Encampment", 2},
    [119] = {"Westguard Keep", 2},
    [120] = {"Wildhammer Stronghold", 2},
    [121] = {"Wintergarde Keep", 2},
    [122] = {"Wyrmrest Temple", 2},
    [123] = {"Zabra'jin", 2},
    [124] = {"Zim'Torga", 2},
}

-- Flat triples: across, down, index into ns.townInfo. Flat for the same
-- reason Data.lua's are.
ns.towns = {
    {zone = "Arathi Highlands", texture = "Arathi", area = 45,
     points = {
        0.7394,0.3576,52, 0.4612,0.4657,73,
    }},
    {zone = "Ashenvale", texture = "Ashenvale", area = 331,
     points = {
        0.3611,0.5080,10, 0.7395,0.6209,82,
    }},
    {zone = "Azuremyst Isle", texture = "AzuremystIsle", area = 3524,
     points = {
        0.4917,0.5105,12,
    }},
    {zone = "Badlands", texture = "Badlands", area = 3,
     points = {
        0.4337,0.3034,7, 0.0432,0.4745,57,
    }},
    {zone = "Blade's Edge Mountains", texture = "BladesEdgeMountains", area = 3522,
     points = {
        0.6222,0.3921,37, 0.2855,0.5747,67, 0.3688,0.6501,91,
        0.5245,0.5565,109, 0.6045,0.6887,110,
    }},
    {zone = "Bloodmyst Isle", texture = "BloodmystIsle", area = 3525,
     points = {
        0.5490,0.5667,13,
    }},
    {zone = "Borean Tundra", texture = "BoreanTundra", area = 3537,
     points = {
        0.4932,0.1041,16, 0.5706,0.1923,43, 0.7737,0.3779,93,
        0.7750,0.4902,112, 0.5764,0.6812,114, 0.4136,0.5361,117,
    }},
    {zone = "Darkshore", texture = "Darkshore", area = 148,
     points = {
        0.3862,0.4337,11,
    }},
    {zone = "Desolace", texture = "Desolace", area = 405,
     points = {
        0.6506,0.0832,65, 0.2525,0.7038,78,
    }},
    {zone = "Dragonblight", texture = "Dragonblight", area = 65,
     points = {
        0.3648,0.4664,2, 0.4900,0.7472,60, 0.2913,0.5561,84,
        0.7702,0.6242,116, 0.7777,0.4799,121, 0.5980,0.5424,122,
    }},
    {zone = "Dun Morogh", texture = "DunMorogh", area = 1,
     points = {
        0.2880,0.6875,8, 0.5353,0.3484,54,
    }},
    {zone = "Durotar", texture = "Durotar", area = 14,
     points = {
        0.4555,0.1210,69, 0.5263,0.4243,72, 0.5590,0.7455,75,
        0.4237,0.6844,100,
    }},
    {zone = "Duskwood", texture = "Duskwood", area = 10,
     points = {
        0.7422,0.4711,30, 0.1937,0.5755,71,
    }},
    {zone = "Dustwallow Marsh", texture = "Dustwallow", area = 15,
     points = {
        0.4205,0.7307,62, 0.6502,0.4705,106,
    }},
    {zone = "Elwynn Forest", texture = "Elwynn", area = 12,
     points = {
        0.4241,0.6656,49, 0.4940,0.4133,66, 0.3375,0.5246,88,
    }},
    {zone = "Eversong Woods", texture = "EversongWoods", area = 3430,
     points = {
        0.4442,0.7065,39, 0.4877,0.4867,41,
    }},
    {zone = "Feralas", texture = "Feralas", area = 357,
     points = {
        0.7520,0.4378,19, 0.3115,0.4464,42, 0.8951,0.4626,97,
    }},
    {zone = "Ghostlands", texture = "Ghostlands", area = 3433,
     points = {
        0.4653,0.3180,111,
    }},
    {zone = "Grizzly Hills", texture = "GrizzlyHills", area = 394,
     points = {
        0.3195,0.6003,6, 0.6503,0.4745,21, 0.6194,0.8144,24,
        0.2176,0.6475,27, 0.5911,0.2750,118,
    }},
    {zone = "Hellfire Peninsula", texture = "Hellfire", area = 3483,
     points = {
        0.2476,0.6333,40, 0.5555,0.6380,53, 0.2335,0.3886,96,
        0.5491,0.3898,107,
    }},
    {zone = "Hillsbrad Foothills", texture = "Hilsbrad", area = 267,
     points = {
        0.4995,0.5639,81, 0.6148,0.2002,92,
    }},
    {zone = "Howling Fjord", texture = "HowlingFjord", area = 495,
     points = {
        0.6147,0.1657,44, 0.2491,0.5827,56, 0.5296,0.6720,64,
        0.5970,0.6201,113, 0.7877,0.2960,115, 0.3059,0.4292,119,
    }},
    {zone = "Icecrown", texture = "IcecrownGlacier", area = 210,
     points = {
        0.7976,0.7215,29, 0.2003,0.4790,32, 0.4363,0.2387,103,
    }},
    {zone = "Loch Modan", texture = "LochModan", area = 38,
     points = {
        0.3503,0.4685,105,
    }},
    {zone = "Mulgore", texture = "Mulgore", area = 215,
     points = {
        0.4755,0.5988,14, 0.4480,0.7689,20, 0.3929,0.2723,108,
    }},
    {zone = "Nagrand", texture = "Nagrand", area = 3518,
     points = {
        0.5577,0.3704,48, 0.5454,0.7328,94,
    }},
    {zone = "Netherstorm", texture = "Netherstorm", area = 3523,
     points = {
        0.3222,0.6525,9, 0.6626,0.6704,28, 0.4462,0.3596,104,
    }},
    {zone = "Redridge Mountains", texture = "Redridge", area = 44,
     points = {
        0.2905,0.4508,58,
    }},
    {zone = "Shadowmoon Valley", texture = "ShadowmoonValley", area = 3520,
     points = {
        0.6219,0.2986,5, 0.5650,0.5868,74, 0.2987,0.2931,77,
        0.3706,0.5585,120,
    }},
    {zone = "Shattrath City", texture = "ShattrathCity", area = 3703,
     points = {
        0.5400,0.4477,79,
    }},
    {zone = "Sholazar Basin", texture = "SholazarBasin", area = 3711,
     points = {
        0.2690,0.5930,63,
    }},
    {zone = "Silithus", texture = "Silithus", area = 1377,
     points = {
        0.5222,0.3994,25,
    }},
    {zone = "Silvermoon City", texture = "SilvermoonCity", area = 3487,
     points = {
        0.7405,0.8050,80,
    }},
    {zone = "Silverpine Forest", texture = "Silverpine", area = 130,
     points = {
        0.4359,0.4138,102,
    }},
    {zone = "Stonetalon Mountains", texture = "StonetalonMountains", area = 406,
     points = {
        0.3678,0.0792,87, 0.4781,0.6082,89,
    }},
    {zone = "Stranglethorn Vale", texture = "Stranglethorn", area = 33,
     points = {
        0.2717,0.7556,15, 0.3189,0.2843,51,
    }},
    {zone = "Swamp of Sorrows", texture = "SwampOfSorrows", area = 8,
     points = {
        0.4598,0.5381,85,
    }},
    {zone = "Tanaris", texture = "Tanaris", area = 440,
     points = {
        0.5121,0.2748,47,
    }},
    {zone = "Teldrassil", texture = "Teldrassil", area = 141,
     points = {
        0.5909,0.4033,3, 0.3064,0.5538,31, 0.5626,0.6021,34,
    }},
    {zone = "Terokkar Forest", texture = "TerokkarForest", area = 3519,
     points = {
        0.5762,0.5440,4, 0.4938,0.4564,86,
    }},
    {zone = "The Barrens", texture = "Barrens", area = 17,
     points = {
        0.4485,0.5869,22, 0.6220,0.3795,70, 0.5206,0.3061,99,
    }},
    {zone = "The Exodar", texture = "TheExodar", area = 3557,
     points = {
        0.7639,0.5643,101,
    }},
    {zone = "The Hinterlands", texture = "Hinterlands", area = 47,
     points = {
        0.1436,0.4799,1,
    }},
    {zone = "The Storm Peaks", texture = "TheStormPeaks", area = 67,
     points = {
        0.4914,0.6843,18, 0.6646,0.5066,23, 0.2915,0.7418,46,
        0.3644,0.4937,50, 0.4082,0.8591,55,
    }},
    {zone = "Thousand Needles", texture = "ThousandNeedles", area = 400,
     points = {
        0.4573,0.5071,45,
    }},
    {zone = "Tirisfal Glades", texture = "Tirisfal", area = 85,
     points = {
        0.6097,0.5270,17, 0.3198,0.6498,33,
    }},
    {zone = "Westfall", texture = "Westfall", area = 40,
     points = {
        0.4304,0.6930,61, 0.5683,0.4730,76,
    }},
    {zone = "Wetlands", texture = "Wetlands", area = 11,
     points = {
        0.4797,0.7413,35, 0.4742,0.1677,36, 0.1061,0.5532,59,
    }},
    {zone = "Winterspring", texture = "Winterspring", area = 618,
     points = {
        0.6121,0.3824,38,
    }},
    {zone = "Zangarmarsh", texture = "Zangarmarsh", area = 3521,
     points = {
        0.7869,0.6481,26, 0.4187,0.2792,68, 0.1943,0.5078,83,
        0.8494,0.5464,90, 0.6827,0.4933,95, 0.3225,0.5007,123,
    }},
    {zone = "Zul'Drak", texture = "ZulDrak", area = 66,
     points = {
        0.3955,0.6664,98, 0.5934,0.5719,124,
    }},
}
