-- Generated by tools/clientpatch/build_patches.py - do not hand-edit.
-- The display IDs only exist in the client patches this script builds.

-- Lootbot
UPDATE `creature_template_model` SET `CreatureDisplayID` = 33001, `DisplayScale` = 0.14 WHERE `CreatureID` = 16549 AND `Idx` = 0;
UPDATE `item_template` SET `displayid` = 69001 WHERE `entry` = 23015;
-- Craftbot
UPDATE `creature_template_model` SET `CreatureDisplayID` = 33002, `DisplayScale` = 1.0 WHERE `CreatureID` = 28883 AND `Idx` = 0;
UPDATE `item_template` SET `displayid` = 69002 WHERE `entry` = 39286;
-- Questbot
UPDATE `creature_template_model` SET `CreatureDisplayID` = 33003, `DisplayScale` = 1.0 WHERE `CreatureID` = 24388 AND `Idx` = 0;
UPDATE `item_template` SET `displayid` = 69003 WHERE `entry` = 33816;
-- Bankbot
UPDATE `creature_template_model` SET `CreatureDisplayID` = 33004, `DisplayScale` = 0.45 WHERE `CreatureID` = 25146 AND `Idx` = 0;
UPDATE `item_template` SET `displayid` = 69004 WHERE `entry` = 34518;
-- Auctionbot
UPDATE `creature_template_model` SET `CreatureDisplayID` = 33005, `DisplayScale` = 0.13 WHERE `CreatureID` = 25147 AND `Idx` = 0;
UPDATE `item_template` SET `displayid` = 69005 WHERE `entry` = 34519;
-- Classtrainer
UPDATE `creature_template_model` SET `CreatureDisplayID` = 33006, `DisplayScale` = 1.0 WHERE `CreatureID` = 24480 AND `Idx` = 0;
UPDATE `item_template` SET `displayid` = 69006 WHERE `entry` = 33993;

-- Without a creature_model_info row Creature::InitEntry aborts and the
-- pet never spawns. Its error names creature_template_model - wrong table.
DELETE FROM `creature_model_info` WHERE `DisplayID` IN (33001,33002,33003,33004,33005,33006);
INSERT INTO `creature_model_info` (`DisplayID`,`BoundingRadius`,`CombatReach`,`Gender`,`DisplayID_Other_Gender`) VALUES
(33001,1,1,2,0),   -- Lootbot
(33002,0,0,0,0),   -- Craftbot
(33003,0,0,2,0),   -- Questbot
(33004,0,0,2,0),   -- Bankbot
(33005,0,0,2,0),   -- Auctionbot
(33006,0,0,2,0);   -- Classtrainer
