-- TalentAdvisor builds: the data Core.lua advises from.
--
-- GENERATED by tools/talentadvisor/gen_builds.py from Talent.dbc. Edit the
-- specs there and regenerate; hand edits here are lost and, worse, unchecked.
--
-- A build is an ordered list of steps. Each step names a talent by its place
-- in the tree - tab index, tier, column, all 1-based exactly as
-- GetTalentInfo() reports them - and how many points go there before the plan
-- moves on. The same talent may appear more than once (Improved Shields gets
-- two points early and its third much later), which is what lets a plan say
-- "come back to this" instead of forcing every talent to be filled in one go.
--
-- Position is used instead of names on purpose: names are localised, tiers
-- and columns are not, so a plan written here works on any client language.
-- The names in the trailing comments are for whoever reads this file; the
-- names the addon shows are read live from the game.
--
-- The tab order is the order the trees appear in the talent window
-- (TalentTab.dbc OrderIndex).
--
-- role decides which group the build appears under in the picker, and is what
-- the "what do you want to play" question is asking. school is what a rating
-- with no school on it ("+8 critical strike rating") is taken to mean, so a
-- caster build does not count melee-only ratings and the other way round.
--
-- weights: how many "points" one unit of a stat is worth when ranking gear.
-- Attack power is 1.0 in the physical builds, spell power 1.0 in the casting
-- ones; scores are only ever compared inside one build so the two anchors
-- never meet. Weapon damage is rated per DPS and per hand (DPS_MH, DPS_OH,
-- DPS_2H), and slow weapons get SPEED_MH / SPEED_2H per second of speed above
-- 2.0. These are levelling heuristics, not raid-sim output; /ta weights lists
-- them.
--
-- armorFloor: an armour piece scoring well is still rejected if its armour is
-- below this fraction of what is worn in that slot - that is what stops a
-- healer in plate being told to put on a cloth robe with more Intellect.
--
-- shield: the build fights with something in the off hand, so no two-hander is
-- ever suggested. dualWield says when two one-handers may be paired: true
-- always, { level = n } from that level, { tab, tier, col } once that talent
-- is taken, absent never.

TalentAdvisorBuilds = {
    PALADIN = {
        default = "retribution",

        retribution = {
            name = "Retribution",
            role = "melee",
            school = "melee",
            desc = "Two-handed melee with seals and judgements. The fast way to 80.",
            armorFloor = 0.55,
            spent = { 7, 5, 59 },

            -- {tab, tier, col, points}. 71 points, levels 10-80.
            steps = {
                { 1,  1, 3, 5 }, -- 10-14   Seals of the Pure
                { 3,  1, 3, 5 }, -- 15-19   Benediction
                { 3,  2, 2, 3 }, -- 20-22   Heart of the Crusader
                { 3,  2, 1, 2 }, -- 23-24   Improved Judgements
                { 3,  3, 2, 5 }, -- 25-29   Conviction
                { 3,  3, 3, 1 }, -- 30      Seal of Command
                { 3,  3, 4, 2 }, -- 31-32   Pursuit of Justice
                { 3,  4, 4, 3 }, -- 33-35   Crusade
                { 3,  4, 3, 3 }, -- 36-38   Sanctity of Battle
                { 3,  5, 1, 3 }, -- 39-41   Two-Handed Weapon Specialization
                { 3,  5, 3, 1 }, -- 42      Sanctified Retribution
                { 3,  6, 2, 3 }, -- 43-45   Vengeance
                { 3,  7, 3, 3 }, -- 46-48   Judgements of the Wise
                { 3,  7, 1, 2 }, -- 49-50   The Art of War
                { 3,  7, 2, 1 }, -- 51      Repentance
                { 3,  8, 2, 3 }, -- 52-54   Fanaticism
                { 3,  8, 3, 2 }, -- 55-56   Sanctified Wrath
                { 3,  9, 2, 1 }, -- 57      Crusader Strike
                { 3,  9, 3, 3 }, -- 58-60   Sheath of Light
                { 3,  9, 1, 3 }, -- 61-63   Swift Retribution
                { 3, 10, 2, 3 }, -- 64-66   Righteous Vengeance
                { 3, 11, 2, 1 }, -- 67      Divine Storm
                { 3,  2, 3, 2 }, -- 68-69   Improved Blessing of Might
                { 3,  3, 1, 2 }, -- 70-71   Vindication
                { 3,  6, 3, 2 }, -- 72-73   Divine Purpose
                { 2,  1, 3, 5 }, -- 74-78   Divine Strength
                { 1,  2, 2, 2 }, -- 79-80   Divine Intellect
            },

            weights = {
                STR = 2.4, AGI = 1, STA = 0.6, INT = 0.3, SPI = 0,
                AP = 1, SP = 0.25, CRIT = 1.8, HIT = 2.2, HASTE = 1.4,
                EXP = 2, ARP = 1.1, MP5 = 0.3, HP5 = 0.1, ARMOR = 0.02,
                DEF = 0.2, DODGE = 0.3, PARRY = 0.3, BLOCK = 0, BLOCKR = 0,
                RESIL = 0.3, DPS_MH = 5.5, DPS_OH = 3, DPS_2H = 6, SPEED_MH = 20,
                SPEED_2H = 30,
            },

            notes = {
                "Seals of the Pure first: it is a straight damage increase from level 10 on every seal you own.",
                "Mana is the limit until Judgements of the Wise at 48; Blessing of Wisdom on yourself until then.",
                "Crusader Strike only arrives at 57 - the tree gates it behind 40 points. Until then it is Judgement and Seal procs.",
                "A little Intellect and spell power is weighted in because seals and judgements scale with both.",
            },
        },
        holy = {
            name = "Holy",
            role = "heal",
            school = "spell",
            desc = "Plate healer. Holy Shock at 42, Beacon of Light at 61.",
            shield = true,
            armorFloor = 0.6,
            spent = { 55, 16, 0 },

            -- {tab, tier, col, points}. 71 points, levels 10-80.
            steps = {
                { 1,  1, 2, 5 }, -- 10-14   Spiritual Focus
                { 1,  2, 2, 5 }, -- 15-19   Divine Intellect
                { 1,  2, 1, 3 }, -- 20-22   Healing Light
                { 1,  3, 3, 2 }, -- 23-24   Improved Lay on Hands
                { 1,  3, 2, 5 }, -- 25-29   Illumination
                { 1,  4, 3, 2 }, -- 30-31   Improved Blessing of Wisdom
                { 1,  5, 2, 1 }, -- 32      Divine Favor
                { 1,  5, 3, 3 }, -- 33-35   Sanctified Light
                { 1,  3, 1, 1 }, -- 36      Aura Mastery
                { 1,  6, 3, 5 }, -- 37-41   Holy Power
                { 1,  7, 1, 3 }, -- 42-44   Light's Grace
                { 1,  7, 2, 1 }, -- 45      Holy Shock
                { 1,  8, 3, 5 }, -- 46-50   Holy Guidance
                { 1,  8, 1, 3 }, -- 51-53   Sacred Cleansing
                { 1,  9, 1, 1 }, -- 54      Divine Illumination
                { 1,  9, 3, 5 }, -- 55-59   Judgements of the Pure
                { 1, 10, 2, 2 }, -- 60-61   Infusion of Light
                { 1, 10, 3, 2 }, -- 62-63   Enlightened Judgements
                { 1, 11, 2, 1 }, -- 64      Beacon of Light
                { 2,  1, 2, 5 }, -- 65-69   Divinity
                { 2,  2, 3, 5 }, -- 70-74   Anticipation
                { 2,  2, 2, 2 }, -- 75-76   Guardian's Favor
                { 2,  3, 2, 3 }, -- 77-79   Improved Righteous Fury
                { 2,  3, 1, 1 }, -- 80      Divine Sacrifice
            },

            weights = {
                STR = 0, AGI = 0, STA = 0.3, INT = 0.85, SPI = 0.2,
                AP = 0, SP = 1, CRIT = 0.65, HIT = 0, HASTE = 0.75,
                EXP = 0, ARP = 0, MP5 = 0.7, HP5 = 0.15, ARMOR = 0.02,
                DEF = 0.1, DODGE = 0.1, PARRY = 0, BLOCK = 0, BLOCKR = 0,
                RESIL = 0.2, DPS_MH = 0.4, DPS_OH = 0.2, DPS_2H = 0.5, SPEED_MH = 0,
                SPEED_2H = 0,
            },

            notes = {
                "Intellect is weighted above Spirit: Illumination and Holy Guidance both key off it, Spirit does almost nothing for a paladin.",
                "One-hander and a shield - the gear advice will not offer a two-hander for this build.",
                "Holy Shock at 42 is the first point the spec feels different; Beacon of Light at 61 is the second.",
                "Solo damage is poor. This plan assumes you are healing groups.",
            },
        },
        protection = {
            name = "Protection",
            role = "tank",
            school = "melee",
            desc = "Plate shield tank with Avenger's Shield and Consecration. Holds anything.",
            shield = true,
            armorFloor = 0.6,
            spent = { 0, 54, 17 },

            -- {tab, tier, col, points}. 71 points, levels 10-80.
            steps = {
                { 2,  1, 3, 5 }, -- 10-14   Divine Strength
                { 2,  2, 3, 5 }, -- 15-19   Anticipation
                { 2,  3, 3, 5 }, -- 20-24   Toughness
                { 2,  3, 2, 3 }, -- 25-27   Improved Righteous Fury
                { 2,  1, 2, 5 }, -- 28-32   Divinity
                { 2,  5, 2, 1 }, -- 33      Blessing of Sanctuary
                { 2,  5, 3, 5 }, -- 34-38   Reckoning
                { 2,  6, 1, 2 }, -- 39-40   Sacred Duty
                { 2,  6, 3, 3 }, -- 41-43   One-Handed Weapon Specialization
                { 2,  7, 1, 2 }, -- 44-45   Spiritual Attunement
                { 2,  7, 2, 1 }, -- 46      Holy Shield
                { 2,  7, 3, 3 }, -- 47-49   Ardent Defender
                { 2,  8, 1, 3 }, -- 50-52   Redoubt
                { 2,  8, 3, 3 }, -- 53-55   Combat Expertise
                { 2,  9, 1, 3 }, -- 56-58   Touched by the Light
                { 2,  9, 2, 1 }, -- 59      Avenger's Shield
                { 2, 10, 2, 3 }, -- 60-62   Shield of the Templar
                { 2, 11, 2, 1 }, -- 63      Hammer of the Righteous
                { 3,  1, 3, 5 }, -- 64-68   Benediction
                { 3,  2, 1, 2 }, -- 69-70   Improved Judgements
                { 3,  2, 2, 3 }, -- 71-73   Heart of the Crusader
                { 3,  3, 2, 5 }, -- 74-78   Conviction
                { 3,  3, 4, 2 }, -- 79-80   Pursuit of Justice
            },

            weights = {
                STR = 1, AGI = 1.3, STA = 2.6, INT = 0.5, SPI = 0,
                AP = 0.25, SP = 0.5, CRIT = 0.5, HIT = 0.8, HASTE = 0.4,
                EXP = 1, ARP = 0.1, MP5 = 0.2, HP5 = 0.4, ARMOR = 0.06,
                DEF = 2.6, DODGE = 2.2, PARRY = 2.2, BLOCK = 0.5, BLOCKR = 1.2,
                RESIL = 0.6, DPS_MH = 2.5, DPS_OH = 1.2, DPS_2H = 2, SPEED_MH = 0,
                SPEED_2H = 0,
            },

            notes = {
                "Intellect and spell power carry real weight here - Touched by the Light and Holy Shield mean threat scales with both.",
                "Shield and a one-hander at all times.",
                "Holy Shield at 46 and Avenger's Shield at 59 are the two threat breakpoints; before those, Consecration and Righteous Fury do the work.",
                "Defense rating is the top armour stat until 540 defense at 80.",
            },
        },
        shockadin = {
            name = "Shockadin",
            role = "caster",
            school = "spell",
            desc = "Meta build: Holy Shock as a damage spell, in plate, with a shield. Odd and effective.",
            meta = true,
            shield = true,
            armorFloor = 0.6,
            spent = { 54, 0, 17 },

            -- {tab, tier, col, points}. 71 points, levels 10-80.
            steps = {
                { 1,  1, 3, 5 }, -- 10-14   Seals of the Pure
                { 1,  1, 2, 5 }, -- 15-19   Spiritual Focus
                { 1,  2, 2, 5 }, -- 20-24   Divine Intellect
                { 1,  3, 3, 2 }, -- 25-26   Improved Lay on Hands
                { 1,  3, 2, 5 }, -- 27-31   Illumination
                { 1,  5, 2, 1 }, -- 32      Divine Favor
                { 1,  5, 3, 3 }, -- 33-35   Sanctified Light
                { 1,  3, 1, 1 }, -- 36      Aura Mastery
                { 1,  6, 3, 5 }, -- 37-41   Holy Power
                { 1,  7, 1, 3 }, -- 42-44   Light's Grace
                { 1,  7, 2, 1 }, -- 45      Holy Shock
                { 1,  8, 3, 5 }, -- 46-50   Holy Guidance
                { 1,  9, 3, 5 }, -- 51-55   Judgements of the Pure
                { 1,  7, 3, 3 }, -- 56-58   Blessed Life
                { 1, 10, 2, 2 }, -- 59-60   Infusion of Light
                { 1, 10, 3, 2 }, -- 61-62   Enlightened Judgements
                { 1, 11, 2, 1 }, -- 63      Beacon of Light
                { 3,  1, 3, 5 }, -- 64-68   Benediction
                { 3,  2, 1, 2 }, -- 69-70   Improved Judgements
                { 3,  2, 2, 3 }, -- 71-73   Heart of the Crusader
                { 3,  3, 2, 5 }, -- 74-78   Conviction
                { 3,  3, 4, 2 }, -- 79-80   Pursuit of Justice
            },

            weights = {
                STR = 0, AGI = 0, STA = 0.4, INT = 0.7, SPI = 0.15,
                AP = 0, SP = 1, CRIT = 0.9, HIT = 1.2, HASTE = 0.95,
                EXP = 0, ARP = 0, MP5 = 0.6, HP5 = 0.1, ARMOR = 0.02,
                DEF = 0.1, DODGE = 0.1, PARRY = 0, BLOCK = 0, BLOCKR = 0,
                RESIL = 0.2, DPS_MH = 0.6, DPS_OH = 0.3, DPS_2H = 0.8, SPEED_MH = 0,
                SPEED_2H = 0,
            },

            notes = {
                "Holy Shock at 42 is the point the build starts working. Before that it plays like a slow Retribution.",
                "Conviction in the Retribution tail raises spell crit as well as melee crit - that is why 20 points go there.",
                "Judgement of Light plus Seal of Righteousness keeps mana and health up between shocks.",
                "Spell power plate barely exists while levelling - mail and even a caster shield are fine, the armour floor allows anything at or above mail.",
            },
        },
    },

    ROGUE = {
        default = "combat",

        combat = {
            name = "Combat",
            role = "melee",
            school = "melee",
            desc = "Sinister Strike with two one-handers. Steady, forgiving, good with any weapon.",
            armorFloor = 0.55,
            dualWield = true,
            spent = { 15, 51, 5 },

            -- {tab, tier, col, points}. 71 points, levels 10-80.
            steps = {
                { 2,  1, 2, 2 }, -- 10-11   Improved Sinister Strike
                { 2,  1, 3, 5 }, -- 12-16   Dual Wield Specialization
                { 2,  2, 4, 5 }, -- 17-21   Precision
                { 2,  2, 1, 2 }, -- 22-23   Improved Slice and Dice
                { 2,  3, 1, 2 }, -- 24-25   Endurance
                { 2,  4, 3, 3 }, -- 26-28   Lightning Reflexes
                { 2,  4, 4, 5 }, -- 29-33   Aggression
                { 2,  5, 2, 1 }, -- 34      Blade Flurry
                { 2,  5, 3, 5 }, -- 35-39   Hack and Slash
                { 2,  6, 2, 2 }, -- 40-41   Weapon Expertise
                { 2,  7, 1, 3 }, -- 42-44   Vitality
                { 2,  7, 2, 1 }, -- 45      Adrenaline Rush
                { 2,  7, 3, 1 }, -- 46      Nerves of Steel
                { 2,  8, 3, 5 }, -- 47-51   Combat Potency
                { 2,  9, 2, 1 }, -- 52      Surprise Attacks
                { 2,  9, 3, 2 }, -- 53-54   Savage Combat
                { 2, 10, 2, 5 }, -- 55-59   Prey on the Weak
                { 2, 11, 2, 1 }, -- 60      Killing Spree
                { 1,  1, 3, 5 }, -- 61-65   Malice
                { 1,  1, 2, 2 }, -- 66-67   Remorseless Attacks
                { 1,  2, 1, 3 }, -- 68-70   Ruthlessness
                { 1,  3, 3, 5 }, -- 71-75   Lethality
                { 3,  1, 1, 5 }, -- 76-80   Relentless Strikes
            },

            weights = {
                STR = 1, AGI = 2.4, STA = 0.5, INT = 0, SPI = 0,
                AP = 1, SP = 0, CRIT = 1.9, HIT = 2.4, HASTE = 1.5,
                EXP = 2, ARP = 1.1, MP5 = 0, HP5 = 0.1, ARMOR = 0.02,
                DEF = 0.2, DODGE = 0.4, PARRY = 0.3, BLOCK = 0, BLOCKR = 0,
                RESIL = 0.3, DPS_MH = 5.5, DPS_OH = 4, DPS_2H = 5, SPEED_MH = 15,
                SPEED_2H = 15,
            },

            notes = {
                "Tier 5 takes Hack and Slash (swords and axes). Move those 5 points to Mace Specialisation if you swing maces.",
                "A slow main hand and a fast off hand: Sinister Strike scales with main-hand damage, Combat Potency with off-hand swings.",
                "Killing Spree at 60 and Adrenaline Rush at 45 are the two cooldowns the build is built around.",
                "The single point in Nerves of Steel is the flex point - Improved Kick or Endurance work just as well there.",
            },
        },
        assassination = {
            name = "Assassination",
            role = "melee",
            school = "melee",
            desc = "Daggers and poisons. Mutilate at 54; before that it is Sinister Strike like everyone else.",
            armorFloor = 0.55,
            dualWield = true,
            spent = { 51, 18, 2 },

            -- {tab, tier, col, points}. 71 points, levels 10-80.
            steps = {
                { 1,  1, 3, 5 }, -- 10-14   Malice
                { 1,  2, 1, 3 }, -- 15-17   Ruthlessness
                { 1,  2, 4, 3 }, -- 18-20   Puncturing Wounds
                { 1,  3, 3, 5 }, -- 21-25   Lethality
                { 1,  3, 1, 1 }, -- 26      Vigor
                { 1,  4, 3, 5 }, -- 27-31   Improved Poisons
                { 1,  4, 2, 3 }, -- 32-34   Vile Poisons
                { 1,  5, 2, 1 }, -- 35      Cold Blood
                { 1,  6, 2, 5 }, -- 36-40   Seal Fate
                { 1,  7, 2, 1 }, -- 41      Overkill
                { 1,  7, 3, 3 }, -- 42-44   Deadened Nerves
                { 1,  8, 1, 3 }, -- 45-47   Focused Attacks
                { 1,  8, 3, 3 }, -- 48-50   Find Weakness
                { 1,  9, 1, 3 }, -- 51-53   Master Poisoner
                { 1,  9, 2, 1 }, -- 54      Mutilate
                { 1, 10, 2, 5 }, -- 55-59   Cut to the Chase
                { 1, 11, 2, 1 }, -- 60      Hunger For Blood
                { 2,  1, 3, 5 }, -- 61-65   Dual Wield Specialization
                { 2,  2, 4, 5 }, -- 66-70   Precision
                { 2,  3, 3, 5 }, -- 71-75   Close Quarters Combat
                { 2,  2, 1, 2 }, -- 76-77   Improved Slice and Dice
                { 2,  4, 3, 1 }, -- 78      Lightning Reflexes
                { 3,  1, 3, 2 }, -- 79-80   Opportunity
            },

            weights = {
                STR = 1, AGI = 2.4, STA = 0.5, INT = 0, SPI = 0,
                AP = 1, SP = 0, CRIT = 2.1, HIT = 2.5, HASTE = 1.5,
                EXP = 2, ARP = 1.1, MP5 = 0, HP5 = 0.1, ARMOR = 0.02,
                DEF = 0.2, DODGE = 0.4, PARRY = 0.3, BLOCK = 0, BLOCKR = 0,
                RESIL = 0.3, DPS_MH = 5, DPS_OH = 4.5, DPS_2H = 5, SPEED_MH = 0,
                SPEED_2H = 0,
            },

            notes = {
                "Daggers in both hands - the plan is built on Puncturing Wounds and Mutilate, both dagger-only.",
                "Weapon speed is not weighted: for daggers the item budget matters, not the swing timer.",
                "Mutilate needs 40 points in the tree, so it lands at 54. Until then the build levels on Sinister Strike and poisons.",
                "Instant Poison main hand, Deadly Poison off hand, from the moment you can buy them.",
            },
        },
        subtlety = {
            name = "Subtlety",
            role = "melee",
            school = "melee",
            desc = "Openers, Hemorrhage and Shadowstep. Strong when you pick the fight, fragile when you do not.",
            armorFloor = 0.55,
            dualWield = true,
            spent = { 17, 0, 54 },

            -- {tab, tier, col, points}. 71 points, levels 10-80.
            steps = {
                { 3,  1, 1, 5 }, -- 10-14   Relentless Strikes
                { 3,  1, 3, 2 }, -- 15-16   Opportunity
                { 3,  2, 3, 3 }, -- 17-19   Camouflage
                { 3,  3, 3, 3 }, -- 20-22   Serrated Blades
                { 3,  3, 2, 1 }, -- 23      Ghostly Strike
                { 3,  3, 1, 2 }, -- 24-25   Elusiveness
                { 3,  4, 2, 3 }, -- 26-28   Initiative
                { 3,  4, 3, 2 }, -- 29-30   Improved Ambush
                { 3,  5, 4, 1 }, -- 31      Hemorrhage
                { 3,  5, 3, 2 }, -- 32-33   Dirty Deeds
                { 3,  5, 2, 1 }, -- 34      Preparation
                { 3,  6, 1, 3 }, -- 35-37   Master of Subtlety
                { 3,  6, 3, 5 }, -- 38-42   Deadliness
                { 3,  7, 2, 1 }, -- 43      Premeditation
                { 3,  7, 3, 3 }, -- 44-46   Cheat Death
                { 3,  8, 2, 5 }, -- 47-51   Sinister Calling
                { 3,  8, 3, 2 }, -- 52-53   Waylay
                { 3,  9, 1, 3 }, -- 54-56   Honor Among Thieves
                { 3,  9, 2, 1 }, -- 57      Shadowstep
                { 3, 10, 2, 5 }, -- 58-62   Slaughter from the Shadows
                { 3, 11, 2, 1 }, -- 63      Shadow Dance
                { 1,  1, 3, 5 }, -- 64-68   Malice
                { 1,  2, 1, 3 }, -- 69-71   Ruthlessness
                { 1,  2, 4, 3 }, -- 72-74   Puncturing Wounds
                { 1,  3, 3, 5 }, -- 75-79   Lethality
                { 1,  3, 1, 1 }, -- 80      Vigor
            },

            weights = {
                STR = 1, AGI = 2.4, STA = 0.5, INT = 0, SPI = 0,
                AP = 1, SP = 0, CRIT = 2, HIT = 2.4, HASTE = 1.2,
                EXP = 2, ARP = 1.3, MP5 = 0, HP5 = 0.1, ARMOR = 0.02,
                DEF = 0.2, DODGE = 0.4, PARRY = 0.3, BLOCK = 0, BLOCKR = 0,
                RESIL = 0.3, DPS_MH = 5.5, DPS_OH = 4, DPS_2H = 5, SPEED_MH = 15,
                SPEED_2H = 15,
            },

            notes = {
                "Hemorrhage at 31 replaces Sinister Strike as the filler and is cheaper on energy.",
                "Master of Subtlety and Initiative reward opening from stealth on every pull - this build wants you to restealth between mobs.",
                "Shadowstep at 57 and Shadow Dance at 63 turn it into the ganking spec proper.",
                "Armor penetration is weighted higher here because Hemorrhage and Backstab are pure weapon damage.",
            },
        },
        riposte = {
            name = "Riposte",
            role = "tank",
            school = "melee",
            desc = "Meta build: parry, Riposte and Vitality in leather. Tanks five-mans nothing else will let a rogue tank.",
            meta = true,
            armorFloor = 0.5,
            dualWield = true,
            spent = { 13, 58, 0 },

            -- {tab, tier, col, points}. 71 points, levels 10-80.
            steps = {
                { 2,  1, 2, 2 }, -- 10-11   Improved Sinister Strike
                { 2,  1, 3, 5 }, -- 12-16   Dual Wield Specialization
                { 2,  2, 2, 3 }, -- 17-19   Deflection
                { 2,  2, 4, 5 }, -- 20-24   Precision
                { 2,  3, 2, 1 }, -- 25      Riposte
                { 2,  3, 1, 2 }, -- 26-27   Endurance
                { 2,  4, 3, 3 }, -- 28-30   Lightning Reflexes
                { 2,  4, 4, 5 }, -- 31-35   Aggression
                { 2,  5, 2, 1 }, -- 36      Blade Flurry
                { 2,  5, 3, 5 }, -- 37-41   Hack and Slash
                { 2,  6, 3, 2 }, -- 42-43   Blade Twisting
                { 2,  6, 2, 2 }, -- 44-45   Weapon Expertise
                { 2,  7, 1, 3 }, -- 46-48   Vitality
                { 2,  7, 2, 1 }, -- 49      Adrenaline Rush
                { 2,  7, 3, 2 }, -- 50-51   Nerves of Steel
                { 2,  2, 1, 2 }, -- 52-53   Improved Slice and Dice
                { 2,  8, 3, 5 }, -- 54-58   Combat Potency
                { 2,  9, 2, 1 }, -- 59      Surprise Attacks
                { 2,  9, 3, 2 }, -- 60-61   Savage Combat
                { 2, 10, 2, 5 }, -- 62-66   Prey on the Weak
                { 2, 11, 2, 1 }, -- 67      Killing Spree
                { 1,  1, 3, 5 }, -- 68-72   Malice
                { 1,  1, 2, 2 }, -- 73-74   Remorseless Attacks
                { 1,  2, 1, 3 }, -- 75-77   Ruthlessness
                { 1,  3, 2, 2 }, -- 78-79   Improved Expose Armor
                { 1,  3, 1, 1 }, -- 80      Vigor
            },

            weights = {
                STR = 0.8, AGI = 2.6, STA = 2.2, INT = 0, SPI = 0,
                AP = 0.5, SP = 0.2, CRIT = 1, HIT = 1.4, HASTE = 0.4,
                EXP = 1.2, ARP = 0.1, MP5 = 0, HP5 = 0.4, ARMOR = 0.05,
                DEF = 1.4, DODGE = 2.4, PARRY = 2.6, BLOCK = 0, BLOCKR = 0,
                RESIL = 0.6, DPS_MH = 3.5, DPS_OH = 2.5, DPS_2H = 2, SPEED_MH = 0,
                SPEED_2H = 0,
            },

            notes = {
                "A rogue has no taunt and no block. This holds five-mans through crowd control and Feint, and it dies to anything that hits back hard.",
                "Riposte at 25 needs a parry to fire - Deflection first, always face the mob.",
                "Agility is doubly weighted: dodge and crit come off the same stat, and Vitality adds 4% on top.",
                "Evasion, Cloak of Shadows, Feint and Sprint are the cooldown rotation. Use Tricks of the Trade on nobody - you are the tank.",
            },
        },
    },

    SHAMAN = {
        default = "enhancement",

        enhancement = {
            name = "Enhancement",
            role = "melee",
            school = "melee",
            desc = "Dual-wield melee. The fastest solo levelling spec the class has.",
            armorFloor = 0.55,
            dualWield = { tab = 2, tier = 7, col = 2 }, -- Dual Wield
            spent = { 9, 62, 0 },

            -- {tab, tier, col, points}. 71 points, levels 10-80.
            steps = {
                { 2,  1, 3, 5 }, -- 10-14   Ancestral Knowledge
                { 2,  2, 3, 2 }, -- 15-16   Improved Ghost Wolf
                { 2,  2, 2, 5 }, -- 17-21   Thundering Strikes
                { 2,  3, 3, 1 }, -- 22      Shamanistic Focus
                { 2,  2, 4, 2 }, -- 23-24   Improved Shields
                { 2,  4, 2, 5 }, -- 25-29   Flurry
                { 2,  3, 1, 3 }, -- 30-32   Elemental Weapons
                { 2,  5, 2, 1 }, -- 33      Spirit Weapons
                { 2,  2, 4, 1 }, -- 34      Improved Shields
                { 2,  5, 3, 3 }, -- 35-37   Mental Dexterity
                { 2,  6, 3, 2 }, -- 38-39   Weapon Mastery
                { 2,  7, 2, 1 }, -- 40      Dual Wield
                { 2,  7, 3, 1 }, -- 41      Stormstrike
                { 2,  6, 3, 1 }, -- 42      Weapon Mastery
                { 2,  7, 1, 3 }, -- 43-45   Dual Wield Specialization
                { 2,  8, 2, 1 }, -- 46      Lava Lash
                { 2,  8, 3, 2 }, -- 47-48   Improved Stormstrike
                { 2,  8, 1, 1 }, -- 49      Static Shock
                { 2,  9, 2, 1 }, -- 50      Shamanistic Rage
                { 2,  9, 1, 3 }, -- 51-53   Mental Quickness
                { 2,  8, 1, 1 }, -- 54      Static Shock
                { 2, 10, 2, 5 }, -- 55-59   Maelstrom Weapon
                { 2, 11, 2, 1 }, -- 60      Feral Spirit
                { 2,  6, 1, 3 }, -- 61-63   Unleashed Rage
                { 2,  4, 3, 5 }, -- 64-68   Toughness
                { 2,  8, 1, 1 }, -- 69      Static Shock
                { 2,  5, 1, 2 }, -- 70-71   Improved Windfury Totem
                { 1,  1, 3, 5 }, -- 72-76   Concussion
                { 1,  2, 3, 3 }, -- 77-79   Elemental Devastation
                { 1,  2, 1, 1 }, -- 80      Call of Flame
            },

            weights = {
                STR = 2.2, AGI = 2, STA = 0.7, INT = 1.1, SPI = 0.1,
                AP = 1, SP = 0.35, CRIT = 1.9, HIT = 2.2, HASTE = 1.3,
                EXP = 1.8, ARP = 1, MP5 = 0.6, HP5 = 0.1, ARMOR = 0.03,
                DEF = 0.2, DODGE = 0.3, PARRY = 0.3, BLOCK = 0.1, BLOCKR = 0,
                RESIL = 0.3, DPS_MH = 5.5, DPS_OH = 3, DPS_2H = 5.5, SPEED_MH = 25,
                SPEED_2H = 25,
            },

            notes = {
                "Imbue: Rockbiter -> Flametongue at 10 -> Windfury on the main hand at 30. From 40 Windfury MH + Flametongue OH (Lava Lash).",
                "Shield: Lightning Shield until 20, Water Shield after.",
                "Weapons: the slowest two-hander you can find until 40, two slow one-handers after.",
                "Intellect is weighted for a melee build on purpose - Mental Quickness turns it into attack power.",
            },
        },
        elemental = {
            name = "Elemental",
            role = "caster",
            school = "spell",
            desc = "Lightning Bolt and Lava Burst from range. Kills at a distance, drinks a lot.",
            armorFloor = 0.55,
            spent = { 57, 0, 14 },

            -- {tab, tier, col, points}. 71 points, levels 10-80.
            steps = {
                { 1,  1, 3, 5 }, -- 10-14   Concussion
                { 1,  1, 2, 5 }, -- 15-19   Convection
                { 1,  3, 2, 1 }, -- 20      Elemental Focus
                { 1,  3, 3, 5 }, -- 21-25   Elemental Fury
                { 1,  2, 1, 3 }, -- 26-28   Call of Flame
                { 1,  2, 2, 3 }, -- 29-31   Elemental Warding
                { 1,  5, 2, 1 }, -- 32      Call of Thunder
                { 1,  5, 1, 2 }, -- 33-34   Elemental Reach
                { 1,  6, 3, 5 }, -- 35-39   Lightning Mastery
                { 1,  7, 2, 1 }, -- 40      Elemental Mastery
                { 1,  6, 1, 3 }, -- 41-43   Elemental Precision
                { 1,  7, 3, 3 }, -- 44-46   Storm, Earth and Fire
                { 1,  8, 2, 2 }, -- 47-48   Elemental Oath
                { 1,  8, 3, 3 }, -- 49-51   Lightning Overload
                { 1,  8, 1, 2 }, -- 52-53   Booming Echoes
                { 1,  9, 2, 1 }, -- 54      Totem of Wrath
                { 1,  9, 3, 3 }, -- 55-57   Lava Flows
                { 1,  9, 1, 3 }, -- 58-60   Astral Shift
                { 1, 10, 2, 5 }, -- 61-65   Shamanism
                { 1, 11, 2, 1 }, -- 66      Thunderstorm
                { 3,  1, 3, 5 }, -- 67-71   Totemic Focus
                { 3,  2, 3, 5 }, -- 72-76   Tidal Focus
                { 3,  3, 1, 3 }, -- 77-79   Improved Water Shield
                { 3,  2, 1, 1 }, -- 80      Improved Reincarnation
            },

            weights = {
                STR = 0, AGI = 0, STA = 0.25, INT = 0.6, SPI = 0.25,
                AP = 0, SP = 1, CRIT = 1, HIT = 1.2, HASTE = 0.95,
                EXP = 0, ARP = 0, MP5 = 0.55, HP5 = 0.1, ARMOR = 0.01,
                DEF = 0.1, DODGE = 0.1, PARRY = 0, BLOCK = 0, BLOCKR = 0,
                RESIL = 0.2, DPS_MH = 0.6, DPS_OH = 0.3, DPS_2H = 0.8, SPEED_MH = 0,
                SPEED_2H = 0,
            },

            notes = {
                "Water Shield from 20 is the mana engine - keep it up, and Improved Water Shield in the tail refills it on crits.",
                "Totems: Searing until Fire Elemental range matters, Wrath of Air / Totem of Wrath once talented.",
                "The last 13 points go into Restoration for Totemic Focus, Tidal Focus and Improved Water Shield - the mana block the raid spec uses.",
            },
        },
        restoration = {
            name = "Restoration",
            role = "heal",
            school = "spell",
            desc = "Dungeon healer. Solo kills are slow - group up, or level Elemental and respec.",
            shield = true,
            armorFloor = 0.55,
            spent = { 0, 12, 59 },

            -- {tab, tier, col, points}. 71 points, levels 10-80.
            steps = {
                { 2,  1, 3, 5 }, -- 10-14   Ancestral Knowledge
                { 3,  1, 2, 5 }, -- 15-19   Improved Healing Wave
                { 3,  1, 3, 5 }, -- 20-24   Totemic Focus
                { 3,  2, 3, 5 }, -- 25-29   Tidal Focus
                { 3,  3, 2, 3 }, -- 30-32   Healing Focus
                { 3,  3, 1, 3 }, -- 33-35   Improved Water Shield
                { 3,  3, 3, 1 }, -- 36      Tidal Force
                { 3,  4, 3, 5 }, -- 37-41   Tidal Mastery
                { 3,  4, 2, 3 }, -- 42-44   Restorative Totems
                { 3,  5, 1, 3 }, -- 45-47   Healing Way
                { 3,  5, 3, 1 }, -- 48      Nature's Swiftness
                { 3,  6, 3, 5 }, -- 49-53   Purification
                { 3,  7, 2, 1 }, -- 54      Mana Tide Totem
                { 3,  8, 1, 2 }, -- 55-56   Blessing of the Eternals
                { 3,  8, 3, 3 }, -- 57-59   Nature's Blessing
                { 3,  8, 2, 2 }, -- 60-61   Improved Chain Heal
                { 3,  9, 1, 3 }, -- 62-64   Ancestral Awakening
                { 3,  9, 2, 1 }, -- 65      Earth Shield
                { 3,  9, 3, 2 }, -- 66-67   Improved Earth Shield
                { 3, 10, 2, 5 }, -- 68-72   Tidal Waves
                { 3, 11, 2, 1 }, -- 73      Riptide
                { 2,  2, 4, 3 }, -- 74-76   Improved Shields
                { 2,  2, 1, 2 }, -- 77-78   Guardian Totems
                { 2,  3, 1, 2 }, -- 79-80   Elemental Weapons
            },

            weights = {
                STR = 0, AGI = 0, STA = 0.3, INT = 0.7, SPI = 0.5,
                AP = 0, SP = 1, CRIT = 0.65, HIT = 0, HASTE = 0.75,
                EXP = 0, ARP = 0, MP5 = 0.9, HP5 = 0.15, ARMOR = 0.01,
                DEF = 0.1, DODGE = 0.1, PARRY = 0, BLOCK = 0, BLOCKR = 0,
                RESIL = 0.2, DPS_MH = 0.4, DPS_OH = 0.2, DPS_2H = 0.5, SPEED_MH = 0,
                SPEED_2H = 0,
            },

            notes = {
                "Solo damage is poor with this plan. It is meant for someone healing dungeons from the teens on.",
                "Ancestral Knowledge comes first because +10% Intellect is mana and crit from level 14 on.",
                "Earth Shield at 65 and Riptide at 73 are the two points where the spec changes how it plays.",
                "The Enhancement tail buys Elemental Weapons, which is a straight +Earthliving buff.",
            },
        },
        tank = {
            name = "Earthwarden",
            role = "tank",
            school = "melee",
            desc = "Meta build: shield, Toughness, Anticipation and Shamanistic Rage. Holds five-mans, not raids.",
            meta = true,
            shield = true,
            armorFloor = 0.6,
            spent = { 0, 53, 18 },

            -- {tab, tier, col, points}. 71 points, levels 10-80.
            steps = {
                { 2,  1, 1, 3 }, -- 10-12   Enhancing Totems
                { 2,  1, 2, 2 }, -- 13-14   Earth's Grasp
                { 2,  2, 2, 5 }, -- 15-19   Thundering Strikes
                { 2,  2, 4, 3 }, -- 20-22   Improved Shields
                { 2,  2, 1, 2 }, -- 23-24   Guardian Totems
                { 2,  3, 4, 3 }, -- 25-27   Anticipation
                { 2,  4, 3, 5 }, -- 28-32   Toughness
                { 2,  4, 2, 5 }, -- 33-37   Flurry
                { 2,  3, 1, 3 }, -- 38-40   Elemental Weapons
                { 2,  3, 3, 1 }, -- 41      Shamanistic Focus
                { 2,  6, 3, 3 }, -- 42-44   Weapon Mastery
                { 2,  7, 3, 1 }, -- 45      Stormstrike
                { 2,  8, 3, 2 }, -- 46-47   Improved Stormstrike
                { 2,  8, 1, 3 }, -- 48-50   Static Shock
                { 2,  6, 1, 3 }, -- 51-53   Unleashed Rage
                { 2,  9, 2, 1 }, -- 54      Shamanistic Rage
                { 2,  9, 3, 2 }, -- 55-56   Earthen Power
                { 2, 10, 2, 5 }, -- 57-61   Maelstrom Weapon
                { 2, 11, 2, 1 }, -- 62      Feral Spirit
                { 3,  1, 2, 5 }, -- 63-67   Improved Healing Wave
                { 3,  1, 3, 5 }, -- 68-72   Totemic Focus
                { 3,  3, 2, 3 }, -- 73-75   Healing Focus
                { 3,  3, 4, 3 }, -- 76-78   Ancestral Healing
                { 3,  3, 1, 2 }, -- 79-80   Improved Water Shield
            },

            weights = {
                STR = 1, AGI = 1.3, STA = 2.6, INT = 0.5, SPI = 0,
                AP = 0.25, SP = 0.3, CRIT = 0.5, HIT = 0.8, HASTE = 0.4,
                EXP = 1, ARP = 0.1, MP5 = 0.3, HP5 = 0.4, ARMOR = 0.06,
                DEF = 1.6, DODGE = 2.2, PARRY = 2.2, BLOCK = 0.2, BLOCKR = 0.3,
                RESIL = 0.6, DPS_MH = 2.5, DPS_OH = 1.2, DPS_2H = 2, SPEED_MH = 0,
                SPEED_2H = 0,
            },

            notes = {
                "A shaman cannot reach crit immunity - this holds normal five-mans, not raid bosses.",
                "Shield in the off hand at all times, Rockbiter on the weapon, Lightning Shield up for threat.",
                "Stoneclaw Totem with Guardian Totems is the panic button; Shamanistic Rage at 54 is the real cooldown.",
                "Maelstrom Weapon plus instant Healing Wave is how the build stays alive once mobs hit harder.",
            },
        },
    },

    WARRIOR = {
        default = "arms",

        arms = {
            name = "Arms",
            role = "melee",
            school = "melee",
            desc = "Two-hander, Mortal Strike, big Overpower and Slam hits. The standard levelling spec.",
            armorFloor = 0.55,
            spent = { 57, 14, 0 },

            -- {tab, tier, col, points}. 71 points, levels 10-80.
            steps = {
                { 1,  1, 1, 3 }, -- 10-12   Improved Heroic Strike
                { 1,  1, 3, 2 }, -- 13-14   Improved Rend
                { 1,  2, 1, 2 }, -- 15-16   Improved Charge
                { 1,  2, 3, 3 }, -- 17-19   Tactical Mastery
                { 1,  3, 3, 2 }, -- 20-21   Impale
                { 1,  3, 4, 3 }, -- 22-24   Deep Wounds
                { 1,  4, 2, 3 }, -- 25-27   Two-Handed Weapon Specialization
                { 1,  4, 3, 3 }, -- 28-30   Taste for Blood
                { 1,  5, 1, 5 }, -- 31-35   Poleaxe Specialization
                { 1,  5, 2, 1 }, -- 36      Sweeping Strikes
                { 1,  6, 1, 2 }, -- 37-38   Weapon Mastery
                { 1,  3, 2, 1 }, -- 39      Anger Management
                { 1,  7, 2, 1 }, -- 40      Mortal Strike
                { 1,  7, 4, 2 }, -- 41-42   Improved Slam
                { 1,  7, 3, 2 }, -- 43-44   Strength of Arms
                { 1,  8, 2, 3 }, -- 45-47   Improved Mortal Strike
                { 1,  8, 1, 1 }, -- 48      Juggernaut
                { 1,  8, 3, 2 }, -- 49-50   Unrelenting Assault
                { 1,  9, 1, 3 }, -- 51-53   Sudden Death
                { 1,  9, 2, 1 }, -- 54      Endless Rage
                { 1,  9, 3, 2 }, -- 55-56   Blood Frenzy
                { 1, 10, 2, 5 }, -- 57-61   Wrecking Crew
                { 1, 11, 2, 1 }, -- 62      Bladestorm
                { 1,  6, 4, 2 }, -- 63-64   Trauma
                { 1,  7, 1, 2 }, -- 65-66   Second Wind
                { 2,  1, 1, 3 }, -- 67-69   Armored to the Teeth
                { 2,  1, 3, 5 }, -- 70-74   Cruelty
                { 2,  2, 3, 5 }, -- 75-79   Unbridled Wrath
                { 2,  1, 2, 1 }, -- 80      Booming Voice
            },

            weights = {
                STR = 2.4, AGI = 1, STA = 0.6, INT = 0, SPI = 0,
                AP = 1, SP = 0, CRIT = 1.8, HIT = 2.2, HASTE = 1.4,
                EXP = 2, ARP = 1.1, MP5 = 0, HP5 = 0.1, ARMOR = 0.02,
                DEF = 0.2, DODGE = 0.3, PARRY = 0.3, BLOCK = 0, BLOCKR = 0,
                RESIL = 0.3, DPS_MH = 5.5, DPS_OH = 3, DPS_2H = 6, SPEED_MH = 20,
                SPEED_2H = 30,
            },

            notes = {
                "Tier 5 is a weapon specialisation - the plan takes Poleaxe (axes and polearms). Move those 5 points to Sword or Mace Specialisation if that is what you swing.",
                "Mortal Strike lands at 40, Bladestorm at 62.",
                "The last 14 points are the Fury opener block: Armored to the Teeth, Cruelty, Unbridled Wrath.",
                "Rage is the limit while levelling - Improved Charge and Improved Heroic Strike come first for that reason.",
            },
        },
        fury = {
            name = "Fury",
            role = "melee",
            school = "melee",
            desc = "Dual wield, Bloodthirst, and two two-handers at 66 with Titan's Grip.",
            armorFloor = 0.55,
            dualWield = { level = 20 },
            spent = { 14, 57, 0 },

            -- {tab, tier, col, points}. 71 points, levels 10-80.
            steps = {
                { 2,  1, 1, 3 }, -- 10-12   Armored to the Teeth
                { 2,  1, 3, 5 }, -- 13-17   Cruelty
                { 2,  2, 3, 5 }, -- 18-22   Unbridled Wrath
                { 2,  3, 4, 5 }, -- 23-27   Commanding Presence
                { 2,  4, 1, 5 }, -- 28-32   Dual Wield Specialization
                { 2,  4, 3, 5 }, -- 33-37   Enrage
                { 2,  4, 2, 2 }, -- 38-39   Improved Execute
                { 2,  5, 1, 3 }, -- 40-42   Precision
                { 2,  5, 2, 1 }, -- 43      Death Wish
                { 2,  6, 3, 5 }, -- 44-48   Flurry
                { 2,  7, 1, 3 }, -- 49-51   Intensify Rage
                { 2,  7, 2, 1 }, -- 52      Bloodthirst
                { 2,  8, 4, 5 }, -- 53-57   Improved Berserker Stance
                { 2,  9, 3, 3 }, -- 58-60   Bloodsurge
                { 2, 10, 2, 5 }, -- 61-65   Unending Fury
                { 2, 11, 2, 1 }, -- 66      Titan's Grip
                { 1,  1, 1, 3 }, -- 67-69   Improved Heroic Strike
                { 1,  1, 3, 2 }, -- 70-71   Improved Rend
                { 1,  2, 3, 3 }, -- 72-74   Tactical Mastery
                { 1,  2, 1, 2 }, -- 75-76   Improved Charge
                { 1,  3, 3, 2 }, -- 77-78   Impale
                { 1,  3, 4, 2 }, -- 79-80   Deep Wounds
            },

            weights = {
                STR = 2.4, AGI = 1, STA = 0.6, INT = 0, SPI = 0,
                AP = 1, SP = 0, CRIT = 1.9, HIT = 2.6, HASTE = 1.5,
                EXP = 2, ARP = 1.1, MP5 = 0, HP5 = 0.1, ARMOR = 0.02,
                DEF = 0.2, DODGE = 0.3, PARRY = 0.3, BLOCK = 0, BLOCKR = 0,
                RESIL = 0.3, DPS_MH = 5.5, DPS_OH = 3.5, DPS_2H = 6, SPEED_MH = 20,
                SPEED_2H = 30,
            },

            notes = {
                "Dual wield opens at 20 from the trainer, not from a talent - the gear advice starts pairing one-handers there.",
                "Titan's Grip at 66 flips the advice back to two-handers: from then on two of them, one in each hand.",
                "Hit rating matters more here than for any other warrior build - two weapons miss twice.",
                "The 14-point Arms tail is Deep Wounds and the rage talents, not Mortal Strike.",
            },
        },
        protection = {
            name = "Protection",
            role = "tank",
            school = "melee",
            desc = "Shield tank. Instant dungeon queues from the teens on, slow solo kills.",
            shield = true,
            armorFloor = 0.6,
            spent = { 16, 3, 52 },

            -- {tab, tier, col, points}. 71 points, levels 10-80.
            steps = {
                { 3,  1, 1, 2 }, -- 10-11   Improved Bloodrage
                { 3,  1, 2, 5 }, -- 12-16   Shield Specialization
                { 3,  1, 3, 3 }, -- 17-19   Improved Thunder Clap
                { 3,  2, 3, 5 }, -- 20-24   Anticipation
                { 3,  2, 2, 3 }, -- 25-27   Incite
                { 3,  3, 4, 5 }, -- 28-32   Toughness
                { 3,  3, 2, 2 }, -- 33-34   Improved Revenge
                { 3,  3, 1, 1 }, -- 35      Last Stand
                { 3,  3, 3, 2 }, -- 36-37   Shield Mastery
                { 3,  5, 2, 1 }, -- 38      Concussion Blow
                { 3,  6, 3, 5 }, -- 39-43   One-Handed Weapon Specialization
                { 3,  7, 2, 1 }, -- 44      Vigilance
                { 3,  7, 3, 3 }, -- 45-47   Focused Rage
                { 3,  8, 2, 3 }, -- 48-50   Vitality
                { 3,  9, 2, 1 }, -- 51      Devastate
                { 3,  9, 1, 1 }, -- 52      Warbringer
                { 3,  9, 3, 3 }, -- 53-55   Critical Block
                { 3, 10, 2, 3 }, -- 56-58   Sword and Board
                { 3, 10, 3, 2 }, -- 59-60   Damage Shield
                { 3, 11, 2, 1 }, -- 61      Shockwave
                { 2,  1, 1, 3 }, -- 62-64   Armored to the Teeth
                { 1,  1, 1, 3 }, -- 65-67   Improved Heroic Strike
                { 1,  1, 2, 5 }, -- 68-72   Deflection
                { 1,  1, 3, 2 }, -- 73-74   Improved Rend
                { 1,  2, 3, 3 }, -- 75-77   Tactical Mastery
                { 1,  2, 2, 3 }, -- 78-80   Iron Will
            },

            weights = {
                STR = 1, AGI = 1.3, STA = 2.6, INT = 0, SPI = 0,
                AP = 0.25, SP = 0.2, CRIT = 0.5, HIT = 0.8, HASTE = 0.4,
                EXP = 1, ARP = 0.1, MP5 = 0, HP5 = 0.4, ARMOR = 0.06,
                DEF = 2.6, DODGE = 2.2, PARRY = 2.2, BLOCK = 0.5, BLOCKR = 1.2,
                RESIL = 0.6, DPS_MH = 2.5, DPS_OH = 1.2, DPS_2H = 2, SPEED_MH = 0,
                SPEED_2H = 0,
            },

            notes = {
                "Shield and a one-hander at all times - the gear advice will not offer a two-hander for this build.",
                "Defense rating is the most valuable stat on an item until 540 defense at 80; it is weighted that way here.",
                "Devastate at 51 and Shockwave at 61 are the threat breakpoints.",
                "Solo damage is low - this build assumes you are tanking groups.",
            },
        },
        gladiator = {
            name = "Gladiator",
            role = "melee",
            school = "melee",
            desc = "Meta build: damage with a shield up. Deep Wounds and Rend early, Sword and Board late.",
            meta = true,
            shield = true,
            armorFloor = 0.55,
            spent = { 20, 0, 51 },

            -- {tab, tier, col, points}. 71 points, levels 10-80.
            steps = {
                { 1,  1, 1, 3 }, -- 10-12   Improved Heroic Strike
                { 1,  1, 3, 2 }, -- 13-14   Improved Rend
                { 1,  2, 3, 3 }, -- 15-17   Tactical Mastery
                { 1,  2, 1, 2 }, -- 18-19   Improved Charge
                { 1,  3, 3, 2 }, -- 20-21   Impale
                { 1,  3, 4, 3 }, -- 22-24   Deep Wounds
                { 1,  3, 2, 1 }, -- 25      Anger Management
                { 1,  4, 3, 3 }, -- 26-28   Taste for Blood
                { 1,  3, 1, 1 }, -- 29      Improved Overpower
                { 3,  1, 1, 2 }, -- 30-31   Improved Bloodrage
                { 3,  1, 2, 5 }, -- 32-36   Shield Specialization
                { 3,  1, 3, 3 }, -- 37-39   Improved Thunder Clap
                { 3,  2, 3, 5 }, -- 40-44   Anticipation
                { 3,  2, 2, 3 }, -- 45-47   Incite
                { 3,  3, 4, 5 }, -- 48-52   Toughness
                { 3,  3, 2, 2 }, -- 53-54   Improved Revenge
                { 3,  3, 3, 2 }, -- 55-56   Shield Mastery
                { 3,  5, 2, 1 }, -- 57      Concussion Blow
                { 3,  6, 3, 5 }, -- 58-62   One-Handed Weapon Specialization
                { 3,  7, 3, 3 }, -- 63-65   Focused Rage
                { 3,  8, 2, 3 }, -- 66-68   Vitality
                { 3,  4, 3, 3 }, -- 69-71   Puncture
                { 3,  9, 2, 1 }, -- 72      Devastate
                { 3,  9, 3, 3 }, -- 73-75   Critical Block
                { 3, 10, 2, 3 }, -- 76-78   Sword and Board
                { 3, 10, 3, 2 }, -- 79-80   Damage Shield
            },

            weights = {
                STR = 2.4, AGI = 1, STA = 1.2, INT = 0, SPI = 0,
                AP = 1, SP = 0, CRIT = 1.8, HIT = 2.2, HASTE = 1.4,
                EXP = 2, ARP = 1.1, MP5 = 0, HP5 = 0.1, ARMOR = 0.03,
                DEF = 0.8, DODGE = 0.8, PARRY = 0.8, BLOCK = 0.8, BLOCKR = 0.6,
                RESIL = 0.3, DPS_MH = 5.5, DPS_OH = 3, DPS_2H = 6, SPEED_MH = 20,
                SPEED_2H = 30,
            },

            notes = {
                "Arms damage talents first, the Protection half from 30 - so it plays like Arms with a shield for the first twenty levels.",
                "Devastate only lands at 72; until then Sunder Armor and Revenge carry the shield half.",
                "Block value is weighted because Shield Slam scales with it.",
                "Slower to kill than Arms, far harder to kill. Good for pulling several mobs at once.",
            },
        },
    },
}
