#!/usr/bin/env bash
# Wraps env/dist/bin/worldserver so that running `./worldserver` also starts
# the live dashboard, and stopping worldserver also stops the dashboard.
#
# Idempotent and safe to re-run after every `make install` (which overwrites
# `worldserver` with the plain binary again, undoing the wrap) - run this
# script again afterwards to re-wrap it.
#
# Usage: modules/mod-live-dashboard/webapp/install-worldserver-wrapper.sh [bin_dir]
#   bin_dir defaults to env/dist/bin relative to the repo root.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
BIN_DIR="${1:-$REPO_ROOT/env/dist/bin}"

if [ ! -d "$BIN_DIR" ]; then
    echo "Bin directory not found: $BIN_DIR" >&2
    exit 1
fi

cd "$BIN_DIR"

if [ ! -f worldserver ]; then
    echo "No worldserver binary found in $BIN_DIR - run 'make install' first." >&2
    exit 1
fi

# Detect whether `worldserver` is currently the real ELF binary (fresh from
# `make install`) or already our wrapper script, by checking for a shebang.
if head -c 2 worldserver | grep -q '^#!'; then
    if [ ! -f worldserver.bin ]; then
        echo "worldserver looks like a wrapper already, but worldserver.bin is missing." >&2
        echo "Run 'make install' again, then re-run this script." >&2
        exit 1
    fi
    echo "worldserver is already wrapped, refreshing the wrapper script."
else
    mv -f worldserver worldserver.bin
    echo "Moved the real binary to worldserver.bin."
fi

cat > worldserver <<WRAPPER
#!/usr/bin/env bash
# Auto-generated by install-worldserver-wrapper.sh - do not edit by hand,
# re-run that script instead. Starts the live dashboard alongside
# worldserver.bin and stops it again when worldserver exits.
set -uo pipefail
DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
LOG_DIR="\$DIR/../logs"
mkdir -p "\$LOG_DIR"

# Avoid a second instance fighting over the port if one is already running.
pkill -f "mod-live-dashboard/webapp/server.py" 2>/dev/null || true
sleep 0.3

python3 "$REPO_ROOT/modules/mod-live-dashboard/webapp/server.py" >>"\$LOG_DIR/dashboard.log" 2>&1 &
DASH_PID=\$!
echo "[worldserver wrapper] live dashboard started (pid \$DASH_PID) - http://127.0.0.1:8787, log: \$LOG_DIR/dashboard.log"

cleanup() {
    echo "[worldserver wrapper] stopping live dashboard (pid \$DASH_PID)"
    kill "\$DASH_PID" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

"\$DIR/worldserver.bin" "\$@"
WRAPPER

chmod +x worldserver
echo "Done. Run ./worldserver as usual - it now also manages the live dashboard."
