#!/usr/bin/env python3
"""Read Talent.dbc / TalentTab.dbc / Spell.dbc and write the talent trees out.

Two consumers:
  talents.json  - the machine form gen_builds.py resolves talent names against
  trees.lua     - the same data as a Lua table, so run_tests.lua can play the
                  shipped builds through the real trees without a client

Usage: dump_trees.py [<dbc dir>] [<out dir>]
Defaults: env/dist/data/dbc of the AzerothCore checkout, and this directory.
"""
import json
import os
import struct
import sys

CLASS = {1: 'WARRIOR', 2: 'PALADIN', 4: 'HUNTER', 8: 'ROGUE', 16: 'PRIEST',
         32: 'DEATHKNIGHT', 64: 'SHAMAN', 128: 'MAGE', 256: 'WARLOCK', 1024: 'DRUID'}

# 3.3.5a field offsets. Talent.dbc: id, tab, row, col, spell rank 1-9,
# prereq talent 1-3, prereq rank 1-3 (0-based rank index). TalentTab.dbc:
# id, name (17 locale fields), icon, racemask, classmask, petmask, order.
# Spell.dbc: name_lang starts at 136.
TALENT_RANKS = slice(4, 13)
TALENT_PREREQ = slice(13, 16)
TALENT_PREREQ_RANK = slice(16, 19)
TAB_CLASSMASK, TAB_PETMASK, TAB_ORDER = 20, 21, 22
SPELL_NAME = 136


class DBC:
    def __init__(self, path):
        blob = open(path, 'rb').read()
        magic, self.count, self.fields, self.recsize, strsize = struct.unpack_from('<4sIIII', blob, 0)
        if magic != b'WDBC':
            raise ValueError('%s is not a DBC file' % path)
        self._blob = blob
        self._base = 20
        self._strings = blob[20 + self.count * self.recsize:][:strsize]

    def __iter__(self):
        for i in range(self.count):
            yield struct.unpack_from('<%dI' % self.fields, self._blob, self._base + i * self.recsize)

    def string(self, offset):
        if not offset:
            return ''
        return self._strings[offset:self._strings.index(b'\0', offset)].decode('utf-8', 'replace')


def read_trees(dbc_dir):
    tabs_dbc = DBC(os.path.join(dbc_dir, 'TalentTab.dbc'))
    talents_dbc = DBC(os.path.join(dbc_dir, 'Talent.dbc'))
    spells = DBC(os.path.join(dbc_dir, 'Spell.dbc'))

    names = {}
    for rec in spells:
        names[rec[0]] = spells.string(rec[SPELL_NAME])

    # Player trees only: a class mask with exactly one class and no pet mask.
    tabs = {}
    for rec in tabs_dbc:
        if rec[TAB_CLASSMASK] in CLASS and rec[TAB_PETMASK] == 0:
            tabs[rec[0]] = {'name': tabs_dbc.string(rec[1]), 'class': CLASS[rec[TAB_CLASSMASK]],
                            'tab': rec[TAB_ORDER] + 1}

    by_tab = {}
    for rec in talents_dbc:
        if rec[1] not in tabs:
            continue
        ranks = [s for s in rec[TALENT_RANKS] if s]
        prereq = [(t, r) for t, r in zip(rec[TALENT_PREREQ], rec[TALENT_PREREQ_RANK]) if t]
        by_tab.setdefault(rec[1], []).append({
            'id': rec[0], 'tier': rec[2] + 1, 'col': rec[3] + 1, 'max': len(ranks),
            'name': names.get(ranks[0], '?'), 'prereq': prereq,
        })

    trees = {}
    for tab_id, entries in by_tab.items():
        meta = tabs[tab_id]
        trees.setdefault(meta['class'], {})[meta['tab']] = {
            'name': meta['name'],
            'talents': sorted(entries, key=lambda e: (e['tier'], e['col'])),
        }

    # Prerequisites reference talent ids; turn them into coordinates plus the
    # rank actually needed (the DBC stores a 0-based rank index).
    where = {}
    for cls, tree in trees.items():
        for tab, data in tree.items():
            for e in data['talents']:
                where[e['id']] = (cls, tab, e['tier'], e['col'], e['name'])
    for cls, tree in trees.items():
        for tab, data in tree.items():
            for e in data['talents']:
                resolved = []
                for talent_id, rank in e['prereq']:
                    if talent_id in where:
                        _, tab2, tier2, col2, name2 = where[talent_id]
                        resolved.append({'tab': tab2, 'tier': tier2, 'col': col2,
                                         'name': name2, 'rank': rank + 1})
                e['prereq'] = resolved
    return trees


def write_lua(trees, path):
    out = ['-- Generated by dump_trees.py from Talent.dbc - do not edit by hand.',
           '-- TalentTrees[CLASS][tab] = { name = <tree>, talents = { {tier, col, max,',
           '-- name, prereq = {tab, tier, col, rank}}, ... } }',
           '', 'TalentTrees = {']
    for cls in sorted(trees):
        out.append('    %s = {' % cls)
        for tab in sorted(trees[cls]):
            data = trees[cls][tab]
            out.append('        [%d] = { name = %s, talents = {' % (tab, lua_str(data['name'])))
            for e in data['talents']:
                pre = ''
                if e['prereq']:
                    p = e['prereq'][0]
                    pre = ', prereq = { %d, %d, %d, %d }' % (p['tab'], p['tier'], p['col'], p['rank'])
                out.append('            { %d, %d, %d, %s%s },' % (e['tier'], e['col'], e['max'],
                                                                  lua_str(e['name']), pre))
            out.append('        } },')
        out.append('    },')
    out.append('}')
    out.append('')
    open(path, 'w').write('\n'.join(out))


def lua_str(s):
    return '"%s"' % s.replace('\\', '\\\\').replace('"', '\\"')


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    dbc = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        here, '..', '..', '..', '..', 'env', 'dist', 'data', 'dbc')
    out = sys.argv[2] if len(sys.argv) > 2 else here
    trees = read_trees(dbc)
    json.dump(trees, open(os.path.join(out, 'talents.json'), 'w'), indent=1, sort_keys=True)
    write_lua(trees, os.path.join(out, 'trees.lua'))
    for cls in sorted(trees):
        tabs = ', '.join('%d:%s(%d)' % (t, trees[cls][t]['name'], len(trees[cls][t]['talents']))
                         for t in sorted(trees[cls]))
        print('%-12s %s' % (cls, tabs))


if __name__ == '__main__':
    main()
