#!/usr/bin/env python3
"""Measure the client's own font and write fontmetrics.lua.

wow_sim.lua lays frames out for real, which means it has to measure strings
for real: a FontString with a left and a right anchor wraps at that width, and
how many lines it takes decides the height of everything anchored below it.
Guessing that is what the old stub did and why layout could not be checked.

WoW renders GameFont* with Fonts/FRIZQT__.TTF at the pixel size named in the
font object ("height" in Fonts.xml), so the advance of a glyph is
advance_units / unitsPerEm * size. That is what this dumps, per size, for the
printable ASCII range, plus the line height from the font's own hhea table.

Usage: fontmetrics.py [<path to FRIZQT__.TTF>] [<out file>]
The default path is the WotLK client next to this checkout; the file may carry
a .disabled suffix, which is how a replaced font is parked.
"""
import os
import sys

from fontTools.ttLib import TTFont

SIZES = [10, 11, 12, 13, 14, 16, 18, 20]
FIRST, LAST = 32, 126

DEFAULT_FONT = os.path.expanduser(
    "~/Games/world-of-warcraft-wrath-of-the-lich-king/drive_c/"
    "world_of_warcraft_wrath_of_the_lich_king/fonts/frizqt__.ttf")


def find_font(path):
    for candidate in (path, path + ".disabled"):
        if os.path.exists(candidate):
            return candidate
    raise SystemExit("no font at %s (nor .disabled)" % path)


def main():
    path = find_font(sys.argv[1] if len(sys.argv) > 1 else DEFAULT_FONT)
    out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "fontmetrics.lua")

    font = TTFont(path, fontNumber=0)
    upem = font["head"].unitsPerEm
    hhea = font["hhea"]
    line_units = hhea.ascent - hhea.descent + hhea.lineGap
    cmap = font.getBestCmap()
    hmtx = font["hmtx"]

    def advance(ch):
        name = cmap.get(ord(ch))
        if name is None:
            name = cmap.get(ord("?"))
        return hmtx[name][0]

    lines = [
        "-- Generated by fontmetrics.py from the client's FRIZQT__.TTF - do not edit.",
        "-- FontMetrics[size] = { lineHeight = <px>, default = <px>, [byte] = <px> }",
        "-- Advances are the font's own, scaled to the pixel size WoW renders at.",
        "",
        "FontMetrics = {",
    ]
    for size in SIZES:
        scale = size / float(upem)
        lines.append("    [%d] = {" % size)
        lines.append("        lineHeight = %.3f, default = %.3f,"
                     % (line_units * scale, advance("n") * scale))
        row = []
        for code in range(FIRST, LAST + 1):
            row.append("[%d] = %.3f," % (code, advance(chr(code)) * scale))
            if len(row) == 6:
                lines.append("        " + " ".join(row))
                row = []
        if row:
            lines.append("        " + " ".join(row))
        lines.append("    },")
    lines.append("}")
    lines.append("")
    open(out, "w").write("\n".join(lines))

    print("%s: unitsPerEm %d, ascent %d, descent %d, lineGap %d"
          % (os.path.basename(path), upem, hhea.ascent, hhea.descent, hhea.lineGap))
    for size in SIZES:
        scale = size / float(upem)
        print("  size %2d  line %.2fpx  'n' %.2fpx  ' ' %.2fpx"
              % (size, line_units * scale, advance("n") * scale, advance(" ") * scale))
    print("wrote %s" % os.path.relpath(out))


if __name__ == "__main__":
    main()
